name: Release Actions Runner

on:
  push:
    branches: ["main"]
    paths:
      - "apps/actions-runner/**"
      - "!apps/actions-runner/metadata.yaml"
      - "!apps/actions-runner/README.md"
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.metadata.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Read metadata.yaml
        id: metadata
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: apps/actions-runner/metadata.yaml

      - name: Set version
        id: version
        run: |
          version=$(echo '${{ steps.metadata.outputs.content }}' | yq .version)
          echo "version=${version}" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    uses: ./.github/workflows/image-build-action.yaml
    permissions:
      contents: read
      packages: write
    with:
      app: actions-runner
      version: ${{ github.event_name == 'workflow_dispatch' && inputs.version || needs.prepare.outputs.version }}
      release: ${{ github.event_name == 'workflow_dispatch' && inputs.release || github.event_name == 'push' }}
